### ISSUE TITLE
[FEATURE REQUEST] Updating the settings when changing them via the clock - Offset for Temp and humidity - Carrier regulation of the brightness

### ISSUE THREAD

**Issue by Beast-Panik** [Blueforcer/awtrix-light#103]
**# Feature Request 01**

I played with the settings and configuration via mqtt today. I work with IOBoker and for testing the MQTT Explorer. Now I noticed that in IOBroker only the first data point was taken over that I have tested "CTEMP".

![01](https://user-images.githubusercontent.com/55361239/235437296-7abc56bd-c01f-43ce-bdd8-dd08605d514d.png)

All other was not created and can not be angeget by me because IOBroker prohibits this, even in the expert settings. 
Now I have not much idea of MQTT, but I see that other values are sent from the clock via MQTT. 
Could you not then also the change of settings on the clock, send to the server?
So the data points would be created and you could also change them in IOBroker whose MQTT server seems to play a special role?

**# Feature Request 02**

Es scheint mir als seien die Sensoren in der uhr nicht ganz korrekt mit den werten, wäre es möglich einen offset via mqtt zu setzen um die werte zu korrigieren?

**# Feature Request 03**

The automatic brightness control reacts quite quickly, which I do not think is necessary and is also somewhat annoying when a TV is in the immediate vicinity, for example. Then the clock rest regulates frequently, which is annoying. Maybe you could implement the possibility of the brightness differences to regulate slower, in certain areas and not at each change, for example?

**Comment by Blueforcer** [comment]
About FR1:
There is no CTEMP topic in mqtt. It seems thats what youve sended. There is only the settings topic and you need to send a json with CTEMP in it (or others).

FR2:
unfortunally the sonsors sits inside the case, so it doesnt messure the outside. No matter wich offset you will set. It will never be accurate because depending on the brightness, how many leds showing wich colors, the matrix produce different heat.

FR3:
Currently not planned. maybe i can make it smoother in one of the next updates
