### ISSUE TITLE
[FEATURE REQUEST] temperature not correkt

### ISSUE THREAD

**Issue by BenAhrdt** [Blueforcer/awtrix-light#154]
The real temperature is 23,5°C and the TC001 displays 32°C
Maybe there can be an Offset?

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: [ eg. v0.66 ]

**Comment by Blueforcer** [comment]
Since the sensor measures the inside of the housing, there are many factors that can lead to deviation. The brightness of the matrix, how many pixels light up in which colour and also the outside temperature.
Unfortunately, you will not be able to set the exact temperature unless you change it almost every hour.
I recommend deactivating the native app and using your own custom app with an external sensor.

**Comment by cebrac** [comment]
Agreed. The sensor is helpful to early detect a faulty charger/battery behaviour though!

**Comment by shyney7** [comment]
> Agreed. The sensor is helpful to early detect a faulty charger/battery behaviour though!

How does the case temperature contribute to detecting a faulty charger?

**Comment by cebrac** [comment]
> How does the case temperature contribute to detecting a faulty charger?

Since the actual **charging regulator** resides within the device itself, an increase in temperature might indicate a fault with it, among other possibile problems.

The sensor can't help detect a faulty **psu**, obviously.
