### ISSUE TITLE
MQTT Boot Loop

### ISSUE THREAD

**Issue by fefi-byte** [Blueforcer/awtrix-light#165]
version: 0.67
MQTT via IOBroker

If I connect the clock via MQTT, it is in a boot loop.
with home assistant there are no problems.
![awtrix-bootloop](https://github.com/Blueforcer/awtrix-light/assets/55361862/1c0ab99e-0d11-4d34-9d6b-0b57a0b4c34f)

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix-light/issues/163

You need to disable "publish own states on subscribe" and "publish own states on connect" in your iobroker adapter

**Comment by DcFamas** [comment]
@Blueforcer I'm now in the bootloop as well.
Installed a new mqtt instance, because I need those two states in the adapter (openDTU needs them).

'cause of Shelly and openDTU the two standard mqtt ports are occupied. So I set the port to 8884.

![grafik](https://github.com/Blueforcer/awtrix-light/assets/35306967/d8262007-6d0c-456a-a5eb-844a0443882c)
![grafik](https://github.com/Blueforcer/awtrix-light/assets/35306967/cdba3ed2-cf71-4b55-9e3c-16b8ea4ff734)
![grafik](https://github.com/Blueforcer/awtrix-light/assets/35306967/cccbf93e-5e30-4029-a78b-db435a57241f)

The pixel clock says:
CHECK 
No UP :(

What does this mean? Best regards :)

**Comment by fefi-byte** [comment]
@DcFamas 
So please adjust. 

![SmartSelect_20230612-171740_Chrome](https://github.com/Blueforcer/awtrix-light/assets/55361862/f012fc9d-7af5-4eff-a70f-c4c3a1888c2a)


> @BlueforcerIch bin jetzt auch im Bootloop. Habe eine neue mqtt-Instanz installiert, da ich diese beiden Zustände im Adapter benötige (openDTU benötigt sie).
> 
> Aufgrund von Shelly und openDTU sind die beiden Standard-MQTT-Ports belegt. Also habe ich den Port auf 8884 eingestellt.
> 
> ![Grafik](https://user-images.githubusercontent.com/35306967/245177970-d8262007-6d0c-456a-a5eb-844a0443882c.png) ![Grafik](https://user-images.githubusercontent.com/35306967/245178101-cdba3ed2-cf71-4b55-9e3c-16b8ea4ff734.png) ![Grafik](https://user-images.githubusercontent.com/35306967/245178230-cccbf93e-5e30-4029-a78b-db435a57241f.png)
> 
> Die Pixeluhr sagt: CHECK No UP :(
> 
> Was bedeutet das? Mit freundlichen Grüßen :)

**Comment by DcFamas** [comment]
wtf, I'm stupid. I changed those both settings for my first instance mqtt.0, which I'm using for openDTU and made the screenshot for the second instance mqtt.1 which I'm using for the pixelwatch.

Thanks for your patience. :)

**Comment by plaetzchen** [comment]
I have the same issue and I can't find any setting in the MQTT add-on of Home Assistant to change the settings. Is there any trick here?

**Comment by nin9s** [comment]
Home is tust supposed to be solved together with Home Assistant ?
This has worked for years but by notify automation now Seems to trigger a restart After 300 secs
