### ISSUE TITLE
[FEATURE REQUEST] Add support for Update entity in HomeAssistant

### ISSUE THREAD

**Issue by syphernl** [Blueforcer/awtrix-light#317]
# Feature Request

### Describe the solution / feature you'd like

It would be nice if an [update entity](https://www.home-assistant.io/integrations/update/) could be made available to HomeAssistant to inform that there is an update available. 
Other MQTT-based integrations (e.g. Zigbee2MQTT) uses the same and makes it easy for the user to see that there is an OTA-update available for Zigbee devices.

### Describe alternatives you've considered

-

**Comment by Blueforcer** [comment]
This feature was removed long time ago because its caused issues to the high RAM consumption for the https requests.
Its better to build your own automation by comparing
https://[raw.githubusercontent.com/Blueforcer/awtrix-light/main/version](https://raw.githubusercontent.com/Blueforcer/awtrix-light/main/version)
with the actual version with an automation
