### ISSUE TITLE
[FEATURE REQUEST] Don't send zero temperature/hum after reboot

### ISSUE THREAD

**Issue by martin131** [Blueforcer/awtrix-light#354]
# Feature Request

### Describe the solution / feature you'd like

After every(?) reboot Awtrix sends zero temperature and humidity to MQTT. Is it possible to send any other value instead? Like Not available?

### Describe alternatives you've considered

As a workaround, I can use fitler in Home Assistant to filter these values.
### Additional context

![image](https://github.com/Blueforcer/awtrix-light/assets/4062374/60239bff-ee65-4c61-ae35-3b7f4583e122)

**Comment by luebbe** [comment]
It would be sufficient to send no value at after reboot until the values are stable. 
* Maybe the temp sensor needs a little "warm up" time, so delaying the temp/humidity reads for a few seconds could help.
* Or maybe the initial zero values are sent before the sensor has been read for the first time?

**Comment by luebbe** [comment]
The same is also true for the battery levels. Here is a chart from MQTT explorer

![grafik](https://github.com/Blueforcer/awtrix-light/assets/3872576/a1d64870-c58a-46d5-bbbe-d88f52d607f2)

you can see that after a reboot, first a value of zero and immediately afterwards a value of >2400 is reported, before awtrix settles on the correct value of about 600. Is this a reading error during the startup phase or an intialization error?
If it is not an initialization error, but a reading error, maybe you could implement a one-dimensional median filter to get rid of the peaks?

**Comment by Blueforcer** [comment]
Many things are possible.
The question is, does it worth the effort?
Currently I don't see any downside of this behavior.

**Comment by luebbe** [comment]
Looking at the code I think that one problem is that the sensor values may not have been read yet, when they are sent for the first time. Both reading and sending interval are set to 10 seconds by default.
So in order to get rid of the zero values it may be sufficient to delay the first call to sendstats until batt/temp/hum/lux have been read at least once. Another option would be to set the first reading interval of the sensor values to less than the sending interval for the first read and then back to 10 seconds after the first read.
I'll check this out and provide a PR if it works.

**Comment by martin131** [comment]
@Blueforcer  In my setup the problem is that I am controlling thermostat with the temperature from awtrix. If the temperature drops to zero, my thermostat turns on.

**Comment by luebbe** [comment]
The first part is done (no PR yet). Zero values are not sent anymore. Here's the graph (from LTR: batt_raw batt_%, temp, hum, ldr_raw). The first two peaks in each graph are reboots with the 0.90 version. The third reboot with my reworked version shows only a peak in batt_raw (high) and ldr_raw (low). The zero values are already sorted out.

![Awtrix_stats](https://github.com/Blueforcer/awtrix-light/assets/3872576/06fe67dd-d54d-4a02-b6c8-19591798a6d7)

I moved the Ulanzi on the second reboot, that's why the ldr_raw value changes (and probably also temp/hum start to creep, because the brightness went up).
Over the weekend I'll try to find time to sort out the peaks in batt_raw and ldr_raw and will provide a PR
