### ISSUE TITLE
[FEATURE REQUEST] Time schedule for brightness / night mode

### ISSUE THREAD

**Issue by Rinyuu** [Blueforcer/awtrix-light#54]
# Feature Request

### Is your feature request related to a problem?

No.

### Describe the solution / feature you'd like

Being able to set the clock into "night mode" between two times set by the user. Brightness will decrease to a custom brightness level during this time. (Maybe would be cool to have the option to also set color calibration to e.g. [255,255,215] to function as a blue light filter!)

### Describe alternatives you've considered

I currently made my own night mode using HTTP API and an Android app, but this is not very reliable and also a lot of work to set up. The original Ulanzi firmware does support setting brightness during a custom timeframe, but I prefer Awtrix for obvious reasons :)

**Comment by Blueforcer** [comment]
Unfortunately, this makes no sense to me, since awtrix is almost exclusively controlled by the smarthome anyway, awtrix can be adapted exactly to your own needs. The effort to design a simple setup for this, where everyone can set their own preferences, is far too high in my eyes.
The only thing that would make sense here is to be able to set the color correction via API.
